#!/usr/bin/bash

# FIXME : better tmpfile

WPDIR="${WPDIR:-/home/$USER/.wallpapers}" # OK !
CURRENTWP="${CURRENTWP:-/home/$USER/.local/wallpaper}" # OK !

ls $WPDIR | grep -v "$(cat $CURRENTWP)" | shuf | sed 1q  > tmpfile && mv tmpfile $CURRENTWP

/usr/bin/feh --no-fehbg --bg-scale $WPDIR/"$(cat .local/wallpaper)"
