#!/bin/bash

win_name=$(xdotool getactivewindow getwindowclassname)

# i3-msg -t get_tree | jq 'recurse(.nodes[])| select(.window_properties.class == "Zathura") | .id '

prompt=$(printf 'Yes\nWorkspace only\nNo' | rofi -dmenu -p "Do you want to close all $win_name windows?" -i)

if [[ $prompt = 'Yes' ]]; then
  i3-msg "[class=$win_name] kill"
elif [[ $prompt = 'Workspace only' ]]; then
  i3-msg "[class=$win_name workspace=__focused__] kill"
fi
