#!/bin/bash

shopt -s globstar

mountdir=$(mktemp -d)
workingdir=$(mktemp -d)
finaldir="$HOME/HDD/Podcast"
titlefile=$(mktemp)

# Check only one device
if [ "$(simple-mtpfs --list-devices | wc -l)" != 1 ]
then
  echo ERREUR
  exit
  # TODO gérer plusieurs devices
fi

simple-mtpfs "$mountdir"

cp "$mountdir"/Android/data/com.bambuna.podcastaddict/files/podcast/**/*.mp3 "$workingdir"/.

exiftool -Album -Title "$workingdir"/*.mp3 > "$titlefile"

nvim -c "source $HOME/.local/podcastrename.vim" \
  -c "setlocal filetype=podcastrename" "$titlefile"

sed -i -e '/^#.*$/d' -e '/^[[:space:]]*$/d' "$titlefile"
cd "$workingdir"

for f in $(grep '^.*\.mp3 Album$' "$titlefile" | awk '{print $1}')
do
  new_name=$(exiftool -v '-filename<${Album;}.%e' "$f" | sed -e '/-->/!d' -e "s/^.* --> '\(.*\)'$/\1/")
  unf -f "$new_name"
done

for f in $(grep '^.*\.mp3 Title$' "$titlefile" | awk '{print $1}')
do
  new_name=$(exiftool -v '-filename<${Title;}.%e' "$f" | sed -e '/-->/!d' -e "s/^.* --> '\(.*\)'$/\1/")
  unf -f "$new_name"
done

mv "$workingdir"/* "$finaldir"/.

rmdir "$workingdir"
rm "$titlefile"

# Unmount
fusermount -u "$mountdir"
rmdir "$mountdir"
