#!/bin/bash

if [ $# -lt 1 ]
then
	echo Error
	echo Usage : podcast_rename "<list_of_files>"
	exit
fi

if [ -e /tmp/podcast_renaming ] 
then
	rm /tmp/podcast_renaming
fi

for file in $@
do
	ext=`exiftool $file | grep '^File Type Extension' | sed 's/^File Type Extension\s*:\s\?\(.*\)$/\1/'`
	exiftool $file | grep '^Album' | sed 's/^Album\s*:\s\?\(.*\)$/\1/' >> /tmp/podcast_renaming
	exiftool $file | grep '^Title' | sed 's/^Title\s*:\s\?\(.*\)$/\1/' >> /tmp/podcast_renaming
	exiftool $file | grep '^Comment' | sed 's/^Comment\s*:\s\?\(.*\)$/\1/' >> /tmp/podcast_renaming

	variable=`cat /tmp/podcast_renaming | fzf --prompt="Choose your prefered file name"`
	variable=`echo "$variable" | sed 's:/:-:g' |sed 's/(//g' | sed 's/)//g'`
	rm /tmp/podcast_renaming
	touch "$variable"
	new_name=`unf -d "$variable" | sed "s/^.* -> '\(.*\)'\s*$/\1/"`
	if [ -e "$variable" ]
	then
		rm "$variable"
	fi
	mv -iv $file $new_name.$ext
done
